### ISSUE TITLE
Degree Rotated inconsistent with odom

### ISSUE THREAD

**Issue by zhuang42** [RoboticaUtnFrba/create_autonomy#240]
I am not sure if it's a firmware bug or package issue. Basically, I write a script to let the robot turn a certain degree, and it works in the gazabo simulation. The problem comes when I apply the same command on the real robot, the robot always turns a **double degree** other than I requested. 

For example, if I request the robot to turn 90 degrees clockwise, it always turns about 180 degrees, but the odom still reports the robot only turns 90 degrees.

My robot firmware might be out of date so I think it could be the problem, please let me know if you have a similar problem. I will update this thread if the new firmware version fixes this.

Sincerely

**Comment by eborghi10** [comment]
I saw the same and reading [iRobot's Open Interface document](https://www.irobotweb.com/~/media/MainSite/PDFs/About/STEM/Create/iRobot_Roomba_600_Open_Interface_Spec.pdf) you can see this note:

> NOTE: Create 2 and Roomba 500/600 firmware versions prior to 3.3.0 return an incorrect value for
sensors measured in millimeters. It is recommended that you read the left and right encoder counts
directly (packets IDs 43 and 44) and do the unit conversion yourself.
To determine the firmware version on your robot, send a 7 via the serial port to reset it. The robot will
print a long welcome message which will include the firmware version, for example:
r3_robot/tags/release-3.3.0.

I didn't check in-depth if it's an issue with the calculations that we're doing or with their code. Since going straight works well I'm suspecting that it's on our side.

But also since I'm using the IMU to detect the orientation, I didn't care about it too much.

**Comment by zhuang42** [comment]
> But also since I'm using the IMU to detect the orientation, I didn't care about it too much.

Yeah I just ordered an IMU and it is still in the delivery. I request an update for firmware from irobot and they are still preparing it. It's better to have two sensors working correctly to estimate a better orientation.

Thanks for replying, will update it if new firmware works well.

**Comment by eborghi10** [comment]
Do they have plans to release a firmware update?

Keep me posted if it works well, please.

**Comment by zhuang42** [comment]
No problem! I was told by irobot that they were working on an update and anticipate being done in a few weeks, but they didn't give a certain release date so I just need to wait
